// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodReviews.Models;

public partial class MenuItem
{
    public int MenuItemId { get; set; }

    public int? RestaurantId { get; set; }

    public string ItemName { get; set; }

    public decimal Price { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public decimal? AverageRating { get; set; }

    public int? TotalReviews { get; set; }

    public virtual Restaurant Restaurant { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}