// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodReviews.Models;

public partial class Restaurant
{
    public int RestaurantId { get; set; }

    public string RestaurantName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string OpeningHours { get; set; }

    public decimal? AverageRating { get; set; }

    public int? TotalReviews { get; set; }

    public virtual ICollection<MenuItem> MenuItems { get; set; } = new List<MenuItem>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}