// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodReviews.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? UserId { get; set; }

    public int? RestaurantId { get; set; }

    public int? MenuItemId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? ReviewDate { get; set; }

    public virtual MenuItem MenuItem { get; set; }

    public virtual Restaurant Restaurant { get; set; }

    public virtual User User { get; set; }
}