// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodReviews.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? RegisterDate { get; set; }
    public bool IsAdmin { get; set; }
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}