// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FoodReviews.Models
{
    public partial class User
    {
        public int UserId { get; set; }

        [Required]
        [MinLength(6, ErrorMessage = "至少需要 6 個字元")]
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [MinLength(6, ErrorMessage = "密碼至少需要 6 個字元")]
        public string Password { get; set; }

        public DateTime? RegisterDate { get; set; }

        public bool IsAdmin { get; set; }

        public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
    }
}